name: Continuous Integration Workflow
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    name: 'build to JS'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node .js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node .js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm run lint
